<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <AssemblyName>psfix</AssemblyName>
    <RootNamespace>PrinterShareFixer.Cli</RootNamespace>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Version>1.4.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrinterShareFixer.Core\PrinterShareFixer.Core.csproj" />
  </ItemGroup>

</Project>
